### ISSUE TITLE
exctract the "second" data (dtb file)

### ISSUE THREAD

**Issue by eldonT** [csimmonds/boot-extract#1]
It would be nice if your tool could also extract the "second" bin from the boot bin.
The "second" data is the dtb data (device tree blob, which describes the board hardware), necessary to properly build and run a self built (mainline or vanilla) kernel for a specific device.

you can then decompile the dtb file with device-tree-compiler package tool :
dtc -I dtb boot.img-second.gz -O dts -o device.dtd

thx

**Comment by csimmonds** [comment]
That is a nice idea. I have just committed a change to do exactly that. Thanks
